# Generated by Django 3.2.22 on 2023-10-07 10:39
import django.db.models.deletion
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Attribute",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(blank=True, max_length=255, null=True)),
                ("mutable", models.BooleanField(default=False)),
                (
                    "input_type",
                    models.CharField(
                        choices=[("select", "select"), ("radio", "radio")],
                        default="select",
                        max_length=10,
                    ),
                ),
                (
                    "default_value",
                    models.CharField(blank=True, default="", max_length=20, null=True),
                ),
                ("values", models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="Storage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "location",
                    models.CharField(
                        choices=[("local", "local"), ("cloud", "cloud")],
                        default="local",
                        max_length=255,
                    ),
                ),
                ("cloud_storage_id", models.IntegerField(default=1)),
            ],
        ),
        migrations.CreateModel(
            name="Project",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("owner_id", models.IntegerField(blank=True, null=True)),
                ("assignee_id", models.IntegerField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "source_storage",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="source",
                        to="core.storage",
                    ),
                ),
                (
                    "target_storage",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="target",
                        to="core.storage",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Label",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(blank=True, max_length=65, null=True)),
                ("color", models.CharField(default="#FF0000", max_length=20)),
                (
                    "label_type",
                    models.CharField(
                        choices=[("S", "S"), ("M", "M")], default="S", max_length=255
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "attributes",
                    models.ManyToManyField(
                        blank=True,
                        default=None,
                        related_name="labels",
                        to="core.Attribute",
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="labels",
                        to="core.project",
                        verbose_name="Projects",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="attribute",
            name="label",
            field=models.ForeignKey(
                blank=True,
                default=None,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                to="core.label",
            ),
        ),
    ]
