# Generated by Django 3.2.22 on 2023-10-07 13:22
from django.db import migrations
from django.db import models

import core.models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0003_annotation_task"),
    ]

    operations = [
        migrations.AlterField(
            model_name="annotation",
            name="annotation_file",
            field=models.FileField(upload_to=core.models.get_upload_path),
        ),
    ]
