# Generated by Django 3.2.22 on 2023-10-07 13:43
import django.db.models.deletion
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0004_alter_annotation_annotation_file"),
    ]

    operations = [
        migrations.AlterField(
            model_name="task",
            name="annotations",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="core.annotation",
            ),
        ),
    ]
