# Generated by Django 3.2.22 on 2023-10-08 09:31
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0008_auto_20231007_2250"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="annotation",
            name="format",
        ),
        migrations.AddField(
            model_name="task",
            name="subset",
            field=models.CharField(
                choices=[
                    ("test", "test"),
                    ("train", "train"),
                    ("validation", "validation"),
                ],
                default="train",
                max_length=64,
            ),
        ),
    ]
