# Generated by Django 3.2.22 on 2023-10-08 09:48
import django.db.models.deletion
from django.conf import settings
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("core", "0009_auto_20231008_1501"),
    ]

    operations = [
        migrations.CreateModel(
            name="Job",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "state",
                    models.CharField(
                        choices=[
                            ("new", "new"),
                            ("in_progress", "in_progress"),
                            ("completed", "completed"),
                            ("rejected", "rejected"),
                        ],
                        default="new",
                        max_length=100,
                    ),
                ),
                (
                    "stage",
                    models.CharField(
                        choices=[
                            ("annotation", "annotation"),
                            ("validation", "validation"),
                            ("acceptance", "acceptance"),
                        ],
                        default="annotation",
                        max_length=100,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "assignee",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="job_assignee",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "guide_id",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="guide",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "project_id",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="core.project",
                    ),
                ),
                (
                    "task_id",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="core.task",
                    ),
                ),
            ],
        ),
    ]
