# Generated by Django 3.2.22 on 2023-10-08 10:42
import django.db.models.deletion
from django.db import migrations
from django.db import models

import core.models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0010_job"),
    ]

    operations = [
        migrations.CreateModel(
            name="Data",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("filename", models.CharField(blank=True, max_length=500, null=True)),
                ("size", models.IntegerField(default=0)),
                ("file", models.FileField(upload_to=core.models.get_upload_path)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.RemoveField(
            model_name="task",
            name="annotations",
        ),
        migrations.DeleteModel(
            name="Annotation",
        ),
        migrations.AddField(
            model_name="task",
            name="data",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="core.data",
            ),
        ),
    ]
