# Generated by Django 3.2.22 on 2023-10-08 11:02
import django.db.models.deletion
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0011_auto_20231008_1612"),
    ]

    operations = [
        migrations.AddField(
            model_name="data",
            name="task",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="associated_task",
                to="core.task",
            ),
        ),
        migrations.RemoveField(
            model_name="task",
            name="data",
        ),
        migrations.AddField(
            model_name="task",
            name="data",
            field=models.ManyToManyField(
                blank=True, related_name="associated_data", to="core.Data"
            ),
        ),
    ]
