# Generated by Django 3.2.22 on 2023-10-08 11:05
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0012_auto_20231008_1632"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="task",
            name="data",
        ),
    ]
