# Generated by Django 3.2.22 on 2023-10-08 12:45
import django.db.models.deletion
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0013_remove_task_data"),
    ]

    operations = [
        migrations.CreateModel(
            name="AnnotationData",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("transcription", models.TextField(blank=True, null=True)),
                ("value", models.CharField(blank=True, max_length=200, null=True)),
                (
                    "arrtribute",
                    models.ForeignKey(
                        blank=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="annotation_attribute",
                        to="core.attribute",
                    ),
                ),
                (
                    "label",
                    models.ForeignKey(
                        blank=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="annotation_label",
                        to="core.label",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Annotation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("start", models.CharField(blank=True, max_length=200, null=True)),
                ("end", models.CharField(blank=True, max_length=200, null=True)),
                ("color", models.CharField(blank=True, max_length=200, null=True)),
                ("name", models.CharField(blank=True, max_length=200, null=True)),
                (
                    "data",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="annotation_data",
                        to="core.annotationdata",
                    ),
                ),
            ],
        ),
    ]
