# Generated by Django 3.2.22 on 2023-10-08 12:59
import django.db.models.deletion
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0014_annotation_annotationdata"),
    ]

    operations = [
        migrations.AddField(
            model_name="annotation",
            name="job",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="annotation_job",
                to="core.job",
            ),
        ),
    ]
