# Generated by Django 3.2.22 on 2023-10-08 17:12
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0015_annotation_job"),
    ]

    operations = [
        migrations.RenameField(
            model_name="annotationdata",
            old_name="arrtribute",
            new_name="attribute",
        ),
    ]
