# Generated by Django 4.2.3 on 2023-10-09 10:43
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0016_rename_arrtribute_annotationdata_attribute"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="label",
            name="color",
        ),
        migrations.AlterField(
            model_name="task",
            name="subset",
            field=models.CharField(
                choices=[
                    ("Test", "Test"),
                    ("Train", "Train"),
                    ("Validation", "Validation"),
                ],
                default="train",
                max_length=64,
            ),
        ),
    ]
