# Generated by Django 3.2.22 on 2023-10-10 07:56
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0016_rename_arrtribute_annotationdata_attribute"),
    ]

    operations = [
        migrations.AlterField(
            model_name="label",
            name="label_type",
            field=models.CharField(
                choices=[("any", "any")], default="any", max_length=255
            ),
        ),
    ]
