# Generated by Django 3.2.22 on 2023-10-10 15:52
import django.db.models.deletion
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0017_alter_label_label_type"),
    ]

    operations = [
        migrations.RenameField(
            model_name="annotationdata",
            old_name="value",
            new_name="name",
        ),
        migrations.RemoveField(
            model_name="annotation",
            name="data",
        ),
        migrations.RemoveField(
            model_name="annotationdata",
            name="attribute",
        ),
        migrations.RemoveField(
            model_name="annotationdata",
            name="transcription",
        ),
        migrations.AddField(
            model_name="annotation",
            name="labels",
            field=models.ManyToManyField(
                blank=True,
                null=True,
                related_name="annotation_data",
                to="core.AnnotationData",
            ),
        ),
        migrations.AddField(
            model_name="annotation",
            name="transcription",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name="AnnotationAttribute",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("value", models.CharField(blank=True, max_length=200, null=True)),
                (
                    "attribute",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="core.attribute",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="annotationdata",
            name="attributes",
            field=models.ManyToManyField(
                blank=True,
                related_name="annotation_attribute",
                to="core.AnnotationAttribute",
            ),
        ),
    ]
