# Generated by Django 4.2.3 on 2023-10-10 07:57
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0017_remove_label_color_alter_task_subset"),
    ]

    operations = [
        migrations.AlterField(
            model_name="label",
            name="label_type",
            field=models.CharField(
                choices=[("any", "any")], default="S", max_length=255
            ),
        ),
    ]
