# Generated by Django 3.2.22 on 2023-10-10 15:56
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0018_auto_20231010_2122"),
    ]

    operations = [
        migrations.RenameField(
            model_name="annotationattribute",
            old_name="value",
            new_name="values",
        ),
    ]
