# Generated by Django 3.2.22 on 2023-10-10 16:24
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0019_rename_value_annotationattribute_values"),
    ]

    operations = [
        migrations.AlterField(
            model_name="annotation",
            name="labels",
            field=models.ManyToManyField(
                blank=True, related_name="annotation_data", to="core.AnnotationData"
            ),
        ),
    ]
