# Generated by Django 3.2.22 on 2023-10-11 10:16
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0018_alter_label_label_type"),
        ("core", "0020_alter_annotation_labels"),
    ]

    operations = []
