# Generated by Django 3.2.22 on 2023-10-21 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0021_merge_20231011_1546'),
    ]

    operations = [
        migrations.AlterField(
            model_name='label',
            name='label_type',
            field=models.CharField(choices=[('any', 'any')], default='any', max_length=255),
        ),
    ]
