# Generated by Django 4.2.3 on 2023-11-27 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0024_organisation'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='organisation',
            name='id',
        ),
        migrations.AlterField(
            model_name='organisation',
            name='organisation_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
