# Generated by Django 4.2.3 on 2023-11-27 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0026_alter_organisation_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='organisation',
            name='updated_date',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
