# Generated by Django 4.2.3 on 2023-11-29 12:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0028_contact_organisation_owner_organisation_contact'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='organisation',
            name='contact',
        ),
        migrations.RemoveField(
            model_name='organisation',
            name='owner',
        ),
        migrations.DeleteModel(
            name='Contact',
        ),
        migrations.DeleteModel(
            name='Organisation',
        ),
    ]
