# Generated by Django 4.2.3 on 2023-11-29 19:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='organization',
            options={},
        ),
    ]
