# Generated by Django 4.2.3 on 2023-11-29 19:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0002_alter_organization_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='organization',
            options={'default_permissions': ()},
        ),
    ]
