# Generated by Django 4.2.3 on 2023-11-30 06:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0003_alter_organization_options'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='membership',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='membership',
            name='user',
        ),
    ]
