# Generated by Django 4.2.14 on 2024-09-06 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("notifications", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="notifications",
            name="id",
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
