"""Add marked_review to data table

Revision ID: 24e9d6374256
Revises: 24d7e5f82362
Create Date: 2019-10-12 17:06:14.113762

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '24e9d6374256'
down_revision = '24d7e5f82362'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('data', sa.Column('marked_review', sa.Boolean(), nullable=False, default=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('data', 'marked_review')
    # ### end Alembic commands ###
