"""Adds hinglish field

Revision ID: 35bf78e807cf
Revises: 47515d1c5d1c
Create Date: 2019-12-23 20:17:33.206085

"""
from alembic import op
from alembic import context
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '35bf78e807cf'
down_revision = '47515d1c5d1c'
branch_labels = None
depends_on = None

def upgrade():
    schema_upgrades()
    if context.get_x_argument(as_dictionary=True).get('data', None):
        data_upgrades()

def downgrade():
    schema_downgrades()
    if context.get_x_argument(as_dictionary=True).get('data', None):
        data_downgrades()

def schema_upgrades():
    """schema upgrade migrations go here."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('transcription', sa.Column('hinglish_transcription', sa.Text(), nullable=False))
    # ### end Alembic commands ###

def schema_downgrades():
    """schema downgrade migrations go here."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('transcription', 'hinglish_transcription')
    # ### end Alembic commands ###

def data_upgrades():
    """Add any optional data upgrade migrations here!"""
    pass

def data_downgrades():
    """Add any optional data downgrade migrations here!"""
    pass
