"""Add created_at and last_modified columns

Revision ID: 54769ba42890
Revises: 1504fa6ff064
Create Date: 2019-10-08 15:06:15.003808

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "54769ba42890"
down_revision = "1504fa6ff064"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "user",
        sa.Column(
            "created_at", sa.DateTime(), nullable=False, server_default=sa.func.now()
        ),
    )
    op.add_column(
        "user",
        sa.Column(
            "last_modified",
            sa.DateTime(),
            nullable=False,
            server_default=sa.func.now(),
            onupdate=sa.func.utc_timestamp(),
        ),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("user", "last_modified")
    op.drop_column("user", "created_at")
    # ### end Alembic commands ###
