"""Changes topics in table

Revision ID: dbdb22debc9e
Revises: c88ec9d5221b
Create Date: 2019-12-23 18:45:56.817692

"""
from alembic import op
from alembic import context
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'dbdb22debc9e'
down_revision = 'c88ec9d5221b'
branch_labels = None
depends_on = None

def upgrade():
    schema_upgrades()
    if context.get_x_argument(as_dictionary=True).get('data', None):
        data_upgrades()

def downgrade():
    schema_downgrades()
    if context.get_x_argument(as_dictionary=True).get('data', None):
        data_downgrades()

def schema_upgrades():
    """schema upgrade migrations go here."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###

def schema_downgrades():
    """schema downgrade migrations go here."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###

def data_upgrades():
    """Add any optional data upgrade migrations here!"""
    op.execute("DELETE FROM topic")
    topic_table = sa.sql.table("topic", sa.sql.column("topic", sa.String))

    op.bulk_insert(
        topic_table,
        [
            {"topic": "Favourite places to visit in India"},
            {"topic": "Pets"},
            {"topic": "Plans after graduation"},
            {"topic": "Should cell phones be used during class?"},
            {"topic": "Pollution"},
            {"topic": "Does school detention do any good in high schools?"},
            {
                "topic": "Is television an effective tool in building the minds of children?"
            },
            {"topic": "Is cloning animals ethical?"},
            {"topic": "Other"},
        ],
    )

def data_downgrades():
    """Add any optional data downgrade migrations here!"""
    op.execute("DELETE FROM topic")
    topic_table = sa.sql.table("topic", sa.sql.column("topic", sa.String))

    op.bulk_insert(
        topic_table,
        [
            {"topic": "Breastfeeding"},
            {"topic": "Danger sign in mother"},
            {"topic": "Danger sign in newborn"},
            {"topic": "Health and happiness in mother"},
            {"topic": "Newborn temperature"},
            {"topic": "Talking and playing with newborn baby"},
            {"topic": "Other"}
        ],
    )
    
