# Generated by Django 4.2.13 on 2024-07-13 14:53

import cvat.apps.engine.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("engine", "0078_alter_cloudstorage_credentials"),
    ]

    operations = [
        migrations.AddField(
            model_name="labeledimage",
            name="accent",
            field=models.TextField(default=""),
        ),
        migrations.AddField(
            model_name="labeledimage",
            name="age",
            field=models.TextField(default=""),
        ),
        migrations.AddField(
            model_name="labeledimage",
            name="emotion",
            field=models.TextField(default=""),
        ),
        migrations.AddField(
            model_name="labeledimage",
            name="gender",
            field=models.TextField(default=""),
        ),
        migrations.AddField(
            model_name="labeledimage",
            name="locale",
            field=models.TextField(default="en"),
        ),
        migrations.AddField(
            model_name="labeledimage",
            name="transcript",
            field=models.TextField(default=""),
        ),
        migrations.AddField(
            model_name="labeledshape",
            name="accent",
            field=models.TextField(default=""),
        ),
        migrations.AddField(
            model_name="labeledshape",
            name="age",
            field=models.TextField(default=""),
        ),
        migrations.AddField(
            model_name="labeledshape",
            name="emotion",
            field=models.TextField(default=""),
        ),
        migrations.AddField(
            model_name="labeledshape",
            name="gender",
            field=models.TextField(default=""),
        ),
        migrations.AddField(
            model_name="labeledshape",
            name="locale",
            field=models.TextField(default="en"),
        ),
        migrations.AddField(
            model_name="labeledshape",
            name="transcript",
            field=models.TextField(default=""),
        ),
        migrations.AddField(
            model_name="labeledtrack",
            name="accent",
            field=models.TextField(default=""),
        ),
        migrations.AddField(
            model_name="labeledtrack",
            name="age",
            field=models.TextField(default=""),
        ),
        migrations.AddField(
            model_name="labeledtrack",
            name="emotion",
            field=models.TextField(default=""),
        ),
        migrations.AddField(
            model_name="labeledtrack",
            name="gender",
            field=models.TextField(default=""),
        ),
        migrations.AddField(
            model_name="labeledtrack",
            name="locale",
            field=models.TextField(default="en"),
        ),
        migrations.AddField(
            model_name="labeledtrack",
            name="transcript",
            field=models.TextField(default=""),
        ),
        migrations.AddField(
            model_name="segment",
            name="ai_audio_annotation_error_msg",
            field=models.CharField(blank=True, default="", max_length=4096, null=True),
        ),
        migrations.AddField(
            model_name="segment",
            name="ai_audio_annotation_status",
            field=models.CharField(
                choices=[
                    ("not started", "NOT_STARTED"),
                    ("in progress", "IN_PROGRESS"),
                    ("completed", "COMPLETED"),
                    ("failed", "FAILED"),
                ],
                default=cvat.apps.engine.models.AI_AUDIO_ANNOTATION_CHOICES[
                    "NOT_STARTED"
                ],
                max_length=32,
            ),
        ),
        migrations.AddField(
            model_name="segment",
            name="ai_audio_annotation_task_id",
            field=models.CharField(blank=True, default="", max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="task",
            name="audio_total_duration",
            field=models.PositiveIntegerField(default=None, null=True),
        ),
        migrations.AddField(
            model_name="task",
            name="segment_duration",
            field=models.PositiveIntegerField(default=None, null=True),
        ),
        migrations.AddField(
            model_name="trackedshape",
            name="accent",
            field=models.TextField(default=""),
        ),
        migrations.AddField(
            model_name="trackedshape",
            name="age",
            field=models.TextField(default=""),
        ),
        migrations.AddField(
            model_name="trackedshape",
            name="emotion",
            field=models.TextField(default=""),
        ),
        migrations.AddField(
            model_name="trackedshape",
            name="gender",
            field=models.TextField(default=""),
        ),
        migrations.AddField(
            model_name="trackedshape",
            name="locale",
            field=models.TextField(default=""),
        ),
        migrations.AddField(
            model_name="trackedshape",
            name="transcript",
            field=models.TextField(default=""),
        ),
        migrations.AlterField(
            model_name="data",
            name="compressed_chunk_type",
            field=models.CharField(
                choices=[
                    ("audio", "AUDIO"),
                    ("video", "VIDEO"),
                    ("imageset", "IMAGESET"),
                    ("list", "LIST"),
                ],
                default=cvat.apps.engine.models.DataChoice["IMAGESET"],
                max_length=32,
            ),
        ),
        migrations.AlterField(
            model_name="data",
            name="original_chunk_type",
            field=models.CharField(
                choices=[
                    ("audio", "AUDIO"),
                    ("video", "VIDEO"),
                    ("imageset", "IMAGESET"),
                    ("list", "LIST"),
                ],
                default=cvat.apps.engine.models.DataChoice["IMAGESET"],
                max_length=32,
            ),
        ),
        migrations.CreateModel(
            name="AIAudioAnnotation",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("start", models.FloatField()),
                ("end", models.FloatField()),
                ("text", models.TextField()),
                (
                    "job",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="engine.job"
                    ),
                ),
            ],
            options={
                "default_permissions": (),
            },
        ),
    ]
