# Generated by Django 4.2.13 on 2024-07-14 11:51

import cvat.apps.engine.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("engine", "0079_labeledimage_accent_labeledimage_age_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="segment",
            name="ai_audio_annotation_error_msg",
        ),
        migrations.RemoveField(
            model_name="segment",
            name="ai_audio_annotation_status",
        ),
        migrations.RemoveField(
            model_name="segment",
            name="ai_audio_annotation_task_id",
        ),
        migrations.AddField(
            model_name="job",
            name="ai_audio_annotation_error_msg",
            field=models.CharField(blank=True, default="", max_length=4096, null=True),
        ),
        migrations.AddField(
            model_name="job",
            name="ai_audio_annotation_status",
            field=models.CharField(
                choices=[
                    ("not started", "NOT_STARTED"),
                    ("in progress", "IN_PROGRESS"),
                    ("completed", "COMPLETED"),
                    ("failed", "FAILED"),
                ],
                default=cvat.apps.engine.models.AI_AUDIO_ANNOTATION_CHOICES[
                    "NOT_STARTED"
                ],
                max_length=32,
            ),
        ),
        migrations.AddField(
            model_name="job",
            name="ai_audio_annotation_task_id",
            field=models.CharField(blank=True, default="", max_length=100, null=True),
        ),
    ]
