# Generated by Django 4.2.13 on 2024-07-31 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("engine", "0080_remove_segment_ai_audio_annotation_error_msg_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="task",
            name="extra_params",
            field=models.BooleanField(default=False, null=True),
        ),
    ]
