# Generated by Django 4.2.13 on 2025-02-18 21:20

import cvat.apps.engine.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("engine", "0082_remove_task_extra_params_taskflags"),
    ]

    operations = [
        migrations.AddField(
            model_name="segment",
            name="time_stamps",
            field=cvat.apps.engine.models.FloatArrayField(blank=True, default=""),
        ),
    ]
