# Generated by Django 4.2.19 on 2025-03-27 20:46

import cvat.apps.engine.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("engine", "0083_segment_time_stamps"),
    ]

    operations = [
        migrations.AlterField(
            model_name="segment",
            name="time_stamps",
            field=cvat.apps.engine.models.FloatArrayField(blank=True, default=[]),
        ),
    ]
