# Generated by Django 4.2.19 on 2025-04-06 23:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("engine", "0084_alter_segment_time_stamps"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="taskflags",
            name="is_commonvoice",
        ),
        migrations.RemoveField(
            model_name="taskflags",
            name="is_librispeech",
        ),
        migrations.RemoveField(
            model_name="taskflags",
            name="is_librivox",
        ),
        migrations.RemoveField(
            model_name="taskflags",
            name="is_tedlium",
        ),
        migrations.RemoveField(
            model_name="taskflags",
            name="is_vctx",
        ),
        migrations.RemoveField(
            model_name="taskflags",
            name="is_voxceleb",
        ),
        migrations.RemoveField(
            model_name="taskflags",
            name="is_voxpopuli",
        ),
        migrations.AddField(
            model_name="taskflags",
            name="is_accent",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="taskflags",
            name="is_age",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="taskflags",
            name="is_end",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="taskflags",
            name="is_gender",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="taskflags",
            name="is_locale",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="taskflags",
            name="is_nationality",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="taskflags",
            name="is_start",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="taskflags",
            name="is_transcription",
            field=models.BooleanField(default=True),
        ),
    ]
