# Generated by Django 4.2.13 on 2025-04-08 09:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("engine", "0085_remove_taskflags_is_commonvoice_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="taskflags",
            old_name="is_nationality",
            new_name="is_emotion",
        ),
    ]
