# Generated by Django 4.2.19 on 2025-05-10 19:39

import cvat.apps.engine.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("engine", "0086_rename_is_nationality_taskflags_is_emotion"),
    ]

    operations = [
        migrations.AddField(
            model_name="segment",
            name="audio_file_index",
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name="task",
            name="total_frames_count",
            field=cvat.apps.engine.models.IntArrayField(default=[], null=True),
        ),
        migrations.AddField(
            model_name="task",
            name="total_jobs_count",
            field=cvat.apps.engine.models.IntArrayField(default=[], null=True),
        ),
        migrations.AlterField(
            model_name="task",
            name="audio_total_duration",
            field=cvat.apps.engine.models.IntArrayField(default=[], null=True),
        ),
    ]
