# Generated by Django 4.2.19 on 2025-06-13 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("engine", "0087_segment_audio_file_index_task_total_frames_count_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="job",
            name="ai_audio_annotation_lang",
            field=models.CharField(blank=True, default="", max_length=128, null=True),
        ),
    ]
