# Generated by Django 4.2.13 on 2024-07-13 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("quality_control", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="annotationconflict",
            name="character_error_rate",
            field=models.FloatField(default=0.0, null=True),
        ),
        migrations.AddField(
            model_name="annotationconflict",
            name="word_error_rate",
            field=models.FloatField(default=0.0, null=True),
        ),
        migrations.AddField(
            model_name="qualitysettings",
            name="cer_threshold",
            field=models.FloatField(default=0.3, null=True),
        ),
        migrations.AddField(
            model_name="qualitysettings",
            name="compare_extra_parameters",
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AddField(
            model_name="qualitysettings",
            name="wer_threshold",
            field=models.FloatField(default=0.3, null=True),
        ),
        migrations.AlterField(
            model_name="annotationconflict",
            name="type",
            field=models.CharField(
                choices=[
                    ("missing_annotation", "MISSING_ANNOTATION"),
                    ("extra_annotation", "EXTRA_ANNOTATION"),
                    ("mismatching_label", "MISMATCHING_LABEL"),
                    ("low_overlap", "LOW_OVERLAP"),
                    ("mismatching_direction", "MISMATCHING_DIRECTION"),
                    ("mismatching_attributes", "MISMATCHING_ATTRIBUTES"),
                    ("mismatching_groups", "MISMATCHING_GROUPS"),
                    ("covered_annotation", "COVERED_ANNOTATION"),
                    ("mismatching_extra_parameters", "MISMATCHING_EXTRA_PARAMETERS"),
                    ("mismatching_transcript", "MISMATCHING_TRANSCRIPT"),
                ],
                max_length=32,
            ),
        ),
    ]
