# Generated by Django 4.2.14 on 2024-09-06 07:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("organizations", "0003_notifications"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Notifications",
        ),
    ]
