"""empty message

Revision ID: 063b15fc4ca4
Revises: b60bb67d1758
Create Date: 2021-05-02 16:32:52.230489

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '063b15fc4ca4'
down_revision = 'b60bb67d1758'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('data', sa.Column('is_deleted', sa.DateTime(), nullable=True))
    op.add_column('label', sa.Column('is_deleted', sa.DateTime(), nullable=True))
    op.add_column('user', sa.Column('is_deleted', sa.DateTime(), nullable=True))
    op.add_column('user_project', sa.Column('is_deleted', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user_project', 'is_deleted')
    op.drop_column('user', 'is_deleted')
    op.drop_column('label', 'is_deleted')
    op.drop_column('data', 'is_deleted')
    # ### end Alembic commands ###
