"""empty message

Revision ID: e1e28decd983
Revises: 063b15fc4ca4
Create Date: 2021-05-02 16:46:55.760634

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e1e28decd983'
down_revision = '063b15fc4ca4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('project', sa.Column('is_deleted', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('project', 'is_deleted')
    # ### end Alembic commands ###
