"""empty message

Revision ID: ffc98d2cb07f
Revises: e1e28decd983
Create Date: 2021-05-02 16:58:36.146492

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ffc98d2cb07f'
down_revision = 'e1e28decd983'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('label_type', sa.Column('is_deleted', sa.DateTime(), nullable=True))
    op.add_column('label_value', sa.Column('is_deleted', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('label_value', 'is_deleted')
    op.drop_column('label_type', 'is_deleted')
    # ### end Alembic commands ###
