name: Regal
on: pull_request
jobs:
  Linter:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup Regal
        uses: StyraInc/setup-regal@v1
        with:
          version: v0.21.3
          submodule: true
      - run: regal lint --format=github cvat/cvat/apps/*/rules